services:
  # # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/uploads  # 持久化存储上传的图片
    depends_on:
      - postgres
    environment:
      - PORT=3001
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=cxc_test
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=24h
      - UPLOAD_DIR=./uploads
    restart: always

  # PostgreSQL 数据库
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # 持久化存储数据库
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cxc_test
    restart: always

volumes:
  postgres-data:  # 数据库卷