services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # 持久化存储数据库
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cxc_test
    restart: always

volumes:
  postgres-data:  # 数据库卷